version: "3.7"
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile

  web:
    image: nginx
    ports:
      - 80:8080
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
